updating file

diff --git a/dataflowscript/Dockerfile b/dataflowscript/Dockerfile
--- a/dataflowscript/Dockerfile
+++ b/dataflowscript/Dockerfile
@@ -9,36 +9,37 @@ FROM python:3.11.15-alpine3.22
 COPY --from=launcher /opt/google/dataflow/python_template_launcher \
                      /opt/google/dataflow/python_template_launcher
 COPY oden_pubsub_to_gcs.py /template/
+COPY requirements.txt      /template/requirements.txt
 
 RUN apk update && \
     apk upgrade && \
     apk add --no-cache openjdk17-jre-headless && \
     rm -rf /tmp/* /var/tmp/*
 
-RUN groupadd --gid 1001 appgroup && \
-    useradd --uid 1001 --gid appgroup \
-            --no-create-home --shell /usr/sbin/nologin appuser
+# RUN groupadd --gid 1001 appgroup && \
+#     useradd --uid 1001 --gid appgroup \
+#             --no-create-home --shell /usr/sbin/nologin appuser
 
 ENV FLEX_TEMPLATE_PYTHON_PY_FILE="/template/oden_pubsub_to_gcs.py"
 ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE="/template/requirements.txt"
 
-COPY --chown=appuser:appgroup requirements.txt      /template/requirements.txt
-COPY --chown=appuser:appgroup oden_pubsub_to_gcs.py /template/oden_pubsub_to_gcs.py
+# COPY requirements.txt      /template/requirements.txt
+# COPY oden_pubsub_to_gcs.py /template/oden_pubsub_to_gcs.py
 
-RUN chmod 550 /template && \
-    chmod 440 /template/requirements.txt \
-              /template/oden_pubsub_to_gcs.py
+# RUN chmod 550 /template && \
+#     chmod 440 /template/requirements.txt \
+#               /template/oden_pubsub_to_gcs.py
 
 RUN pip install --no-cache-dir \
     --root-user-action=ignore \
     -r /template/requirements.txt && \
     pip cache purge
  
-HEALTHCHECK --interval=30s \
-            --timeout=10s \
-            --start-period=15s \
-            --retries=3 \
-    CMD test -x /opt/google/dataflow/python_template_launcher || exit 1
+# HEALTHCHECK --interval=30s \
+#             --timeout=10s \
+#             --start-period=15s \
+#             --retries=3 \
+#     CMD test -x /opt/google/dataflow/python_template_launcher || exit 1
  
 USER appuser
  
